version: '3.8'

services:
  mongodb:
    image: mongo:5.0.9
    container_name: mongodb_busses
    volumes:
      # Named volume to persist database
      - mongodb_busses:/data/db
    env_file:
      - ./.env
    ports:
      - '27018:27017'

volumes:
  mongodb_busses:
